name: RT-TicketWhiteboard
version: 1.0
abstract: RT TicketWhiteboard Extension
author: Jesse Vincent <jesse@bestpractical.com>
license: GPL version 2
distribution_type: module
no_index:
  directory:
    - html
    - inc
generated_by: Module::Install version 0.37
